name: sraph_logger
description: A Dart package for debug and error logging.
version: 1.0.1
homepage: "https://github.com/sraphs/flutter_packages"

environment:
  sdk: ">=2.17.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
